# Use root/12AW-9872-pkDF as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "12AW-9872-pkDF"
      MARIADB_DATABASE: docsig
    ports:
      - 3306:3306
    volumes: 
    - ./docker-create-tables:/docker-entrypoint-initdb.d


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  node:
    build: 
      context: .
      dockerfile: Dockerfile
    user: "pptruser"
    working_dir: /home/pptruser
    environment:
      - DB_HOST=db
      - DB_NAME=docsig
      - DB_USER=root
      - DB_PWD=12AW-9872-pkDF
      - BASEURL="http://localhost:3000"
#    volumes:
#      - ./:/home/node/app
    ports:
      - 3000:3000
    command: "npm run docker-start"      
